server.port=8080
spring.application.name=kafka-deep-dive

spring.kafka.bootstrap-servers=localhost:9095,localhost:9096

enable.scheduled.producer=false
enable.record.consumer=true

topic.name=order-events-topic

spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

## If the producer uses JsonSerializer and add type headers is true by default until you add the property to make it false
# A _TypeId_ header is added for every record if the KafkaTemplate<String, Order> of specific type instead of Object class
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

#--------------- RECORD ACCUMULATOR ---------------
# Batching wait 20ms to collect more messages before sending or 32KB Batch size
spring.kafka.producer.batch-size=32768
spring.kafka.producer.linger-ms=20

#--------------- COMPRESSION ---------------
# Enable compression
spring.kafka.producer.compression-type=snappy

#--------------- RETRIES ---------------
# Enable retries
spring.kafka.producer.retries=3

# Max in flight requests
spring.kafka.producer.max-in-flight-requests-per-connection=5

## problem with retry and max-in-flight-requests-per-connection
# 1. Broker might write duplicate records in to partition
# 2. Message reordering may happen
# To solve the above problem we need to set idempotency = true

# Idempotency
# Prevents Duplicate messages on retry AND preserves ordering with in-flight > 1
# When true, each message gets PID(producer ID) + sequence number
# Broker rejects out-of-order sequences -> forces correct ordering even with retries
# Also forces: acks = all, retries=MAX_INT internally
# Even with idempotence true there is a loophole where there is a chance of duplicate messages
# as the producer or re-start may try sending them again which might be in In_progress
# we can solve this problem with transactions
spring.kafka.producer.properties.enable.idempotence=true


## -------- CONSUMER PROPERTIES --------

spring.kafka.consumer.group-id=order-consumer-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.hans.event.Order
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.properties.spring.json.remove.type.headers=false
spring.kafka.consumer.properties.spring.json.type.mapping=com.hans.event.Order:com.hans.event.Order,com.hans.event.producer.PaymentEvent:com.hans.event.consumer.PaymentEvent,com.hans.event.producer.NotifyEvent:com.hans.event.consumer.NotifyEvent

## Flow at consumer side if _TypeId_ header is present
# 1. For each event we get bytes + headers when we consume using ConsumerRecord
# 2. It checks if the value deserializer is JacksonJsonDeserializer
# 3. If No, it uses custom deserializer
# 4. If yes deserializer is JacksonJsonDeserializer and there is 1 more config in property
# 5. spring.kafka.consumer.properties.spring.json.use.type.headers=true(by default true)
# 6. If no, it will use the default type specified in the property spring.kafka.consumer.properties.spring.json.value.default.type=com.hans.event.Order
# 7. If yes, then it checks if the _TypeId_ header is present
# 8. If no, then it uses the default type specified in the property pring.kafka.consumer.properties.spring.json.value.default.type=com.hans.event.Order
# 9. If yes, then it checks if there is mapping present spring.kafka.consumer.properties.spring.json.value.type.mapping=(from)com.hans.event.Order:(to)com.hans.event.Order
# 10. If yes, then it uses to class and converts to the type specified in the mapping
# 11. If no, mapping not present then it check the _TypeId_ has a TrustedPackage then load the class if exists and deserialize
# 12. If no, TrustedPackage not present then it throws the IllegalArgumentException
# 13. If tursted no class then it throws the ClassNotFoundException




