server.port=8081
spring.application.name=kafka-consumer

spring.kafka.bootstrap-servers=localhost:9095,localhost:9096

topic.name=order-events-topic

## -------- CONSUMER PROPERTIES --------

## Consumer metadata refresh
# By default it is 5 minutes
spring.kafka.consumer.properties.metadata.max.age.ms=5

## Poll timeout
spring.kafka.listener.poll-timeout=5000

## How many messages we can poll from the topic(1MB)
spring.kafka.consumer.properties.max.partition.fetch.bytes=1048576

## Max data(total) the broker can return in one request(52MB)
spring.kafka.consumer.properties.fetch.max.bytes=52428800

## Broker decides when to response
## Minimum data (in bytes) the broker must have before responding
spring.kafka.consumer.properties.fetch.min.bytes=1

## How long broker can hold the request to meet fetch.min.bytes(0.5 sec)
spring.kafka.consumer.properties.fetch.max.wait.ms=500

## Max number of records returned in a single poll() call
## Broker might send more records like 2000 to match the fetch.max.bytes
## But if we configure max poll records as 100 it will keep the remaining 1900 in the
## buffer and next time it will poll 100 from those 1900 instead of going to broker
spring.kafka.consumer.properties.max.poll.records=100

## Can we have gap between polls
spring.kafka.listener.idle-between-polls=5

## how to know if consumer is stuck while processing the events
## or any other issue with consumer
# By setting below property consumer sends Heartbeat Pulse to Group Coordinator every 3 seconds
spring.kafka.consumer.properties.heartbeat.interval.ms=3000

## Max time group coordinator will wait for the heartbeat (generally its higher than heartbeat.interval.ms)
# after this say 45seconds it will Consumer as dead and initiate rebalance
spring.kafka.consumer.properties.session.timeout.ms=45000

## Group Coordinator expects 1 poll() call every 5mins
## If the consumer is not able to process the records within 5 mins
# group coordinator will think that consumer got stuck and initiates rebalance
spring.kafka.consumer.properties.max.poll.interval.ms=300000

## Manual commit offset
# consumer commits offset to the broker manually after processing the records
# By default manual commit is disabled
# To enable manual commit we need to set enable.auto.commit to false
spring.kafka.consumer.properties.enable.auto.commit=false

## default ack mode is batch
## Drawbacks with batch mode is if lets say last message is failed, whole batch needs to retried as the offset is committed
spring.kafka.listener.ack-mode=manual

spring.kafka.consumer.group-id=order-consumer-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.hans.event.consumer.NotifyEvent

## When we are not going to use __TypeId__ header, then we can disable it by setting the below property to false
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.remove.type.headers=false
spring.kafka.consumer.properties.spring.json.type.mapping=com.hans.event.Order:com.hans.event.Order,com.hans.event.producer.PaymentEvent:com.hans.event.consumer.PaymentEvent,com.hans.event.producer.NotifyEvent:com.hans.event.consumer.NotifyEvent
